import Link from "next/link";
import { ArrowLeft } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-black text-white px-6 py-20" style={{ fontFamily: "'Inter', sans-serif" }}>
      <div className="max-w-4xl mx-auto">
        <Link href="/" className="inline-flex items-center gap-2 text-zinc-400 hover:text-white transition-colors mb-12">
          <ArrowLeft className="w-4 h-4" />
          Back to Home
        </Link>
        
        <h1 className="text-4xl md:text-5xl font-bold tracking-tight mb-8">Terms of Service</h1>
        <p className="text-zinc-400 mb-12">Last Updated: July 2026</p>

        <div className="space-y-8 text-zinc-300 leading-relaxed">
          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Avoir.ai ("the Platform"), you agree to be bound by these Terms of Service. If you do not agree, you may not access our services. Avoir.ai is a B2B platform designed for institutional capital, marketing agencies, and enterprise brands.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">2. Subscriptions and Payments</h2>
            <p>
              All subscription fees are billed in advance on a recurring basis via our payment provider, Stripe. You may cancel your subscription at any time, but no refunds will be issued for partial months or unused generation credits.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">3. Acceptable Use Policy</h2>
            <p>
              You agree not to use the Diamond Cascade Engine or any Avoir.ai AI tools to:
            </p>
            <ul className="list-disc pl-6 mt-4 space-y-2">
              <li>Generate illegal, harmful, or explicitly abusive content.</li>
              <li>Attempt to reverse-engineer, exploit, or bypass the platform's security mechanisms.</li>
              <li>Execute automated scraping or API abuse beyond your allotted tier limits.</li>
            </ul>
            <p className="mt-4 text-sm text-red-400">Violation of these terms will result in immediate termination of your account without a refund.</p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">4. Intellectual Property</h2>
            <p>
              <strong>You Own the Output:</strong> Any marketing assets, campaign strategies, and brand DNA generated by Avoir.ai through your prompts belong entirely to you. Avoir.ai claims no ownership over the final generated outputs.
            </p>
            <p className="mt-4">
              <strong>We Own the Engine:</strong> The proprietary algorithms, the Diamond Cascade architecture, the UI/UX, and the Avoir brand are the exclusive intellectual property of Avoir.ai.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-semibold text-white mb-4">5. AI Liability Disclaimer</h2>
            <p>
              Avoir.ai utilizes generative AI models. While our systems are engineered for high-accuracy quantitative generation, AI can occasionally hallucinate or produce inaccurate outputs. 
              <strong> You, the user, are solely responsible for reviewing and validating all AI-generated campaigns before deploying them to live markets.</strong> Avoir.ai is not liable for any financial losses, brand damage, or regulatory penalties incurred from the execution of generated strategies.
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
